In [13]:
import pandas as pd
import numpy as np

In [2]:
# Load data

X_train = pd.read_csv("data/X_train.csv", index_col="ROW_ID")
X_test = pd.read_csv("data/X_test.csv", index_col="ROW_ID")

y_train = pd.read_csv("data/y_train.csv", index_col="ROW_ID")
sample_submission = pd.read_csv("data/sample_submission.csv", index_col="ROW_ID")

In [3]:
X_train.head()

,TS,ALLOCATION,RET_20,RET_19,RET_18,RET_17,RET_16,RET_15,RET_14,RET_13,...,SIGNED_VOLUME_8,SIGNED_VOLUME_7,SIGNED_VOLUME_6,SIGNED_VOLUME_5,SIGNED_VOLUME_4,SIGNED_VOLUME_3,SIGNED_VOLUME_2,SIGNED_VOLUME_1,MEDIAN_DAILY_TURNOVER,GROUP
ROW_ID,,,,,,,,,,,,,,,,,,,,,
0,DATE_0001,ALLOCATION_01,-0.018192,-0.000306,-0.006881,-0.002393,0.000507,-0.001270,-0.002539,0.002830,...,0.818730,0.941014,0.714129,-0.323847,0.525097,0.363601,-0.219328,NaN,0.096905,1
1,DATE_0001,ALLOCATION_02,-0.006394,-0.001059,0.001565,0.000033,0.002829,0.001725,0.000875,-0.002160,...,-1.390336,-0.651784,-0.896826,-0.636931,-1.074450,-0.748884,-0.718912,NaN,0.009974,4
2,DATE_0001,ALLOCATION_03,-0.016587,-0.004517,-0.005306,0.004314,0.006471,-0.005868,-0.005030,-0.001488,...,0.961318,0.452482,1.588321,0.790039,1.394445,0.493521,0.268094,NaN,0.044186,1
3,DATE_0001,ALLOCATION_04,-0.005344,0.002790,0.006937,-0.004246,-0.005051,-0.000330,-0.000117,-0.005209,...,-0.483377,-0.565114,-0.631710,-0.663300,-1.615905,-0.959046,-0.478789,NaN,0.001150,2
4,DATE_0001,ALLOCATION_05,-0.010506,-0.005491,0.007752,-0.012299,0.002191,0.003282,0.000495,-0.003489,...,0.268005,0.757707,1.524626,1.565541,1.563963,1.063209,0.921333,NaN,NaN,4

In [4]:
y_train.columns

Index(['target'], dtype='object')

### FE from Benchmark

In [6]:
from feature_eng import FE_benchmark
X_train, X_test, features = FE_benchmark(X_train, X_test)

In [7]:
len(features)

53

In [8]:
X_train[features].head()

,RET_1,RET_2,RET_3,RET_4,RET_5,RET_6,RET_7,RET_8,RET_9,RET_10,...,AVERAGE_PERF_10,AVERAGE_PERF_15,AVERAGE_PERF_20,ALLOCATIONS_AVERAGE_PERF_3,ALLOCATIONS_AVERAGE_PERF_5,ALLOCATIONS_AVERAGE_PERF_10,ALLOCATIONS_AVERAGE_PERF_15,ALLOCATIONS_AVERAGE_PERF_20,STD_PERF_20,ALLOCATIONS_STD_PERF_20
ROW_ID,,,,,,,,,,,,,,,,,,,,,
0,0.003944,-0.000178,0.001013,0.001514,-0.009067,0.002864,-0.009116,0.003312,0.001350,-0.009898,...,-0.001426,-0.000657,-0.001856,-0.000396,-0.000702,-0.000484,-0.000409,-0.000393,0.005911,0.002714
1,0.002323,0.000670,0.001383,-0.003427,0.000577,0.003323,0.003926,0.002878,-0.000259,-0.000376,...,0.001102,0.000649,0.000335,-0.000396,-0.000702,-0.000484,-0.000409,-0.000393,0.002591,0.002714
2,-0.000238,-0.002696,-0.003926,-0.000569,-0.002528,0.004384,-0.011090,-0.002392,0.006396,-0.006482,...,-0.001914,-0.001678,-0.002040,-0.000396,-0.000702,-0.000484,-0.000409,-0.000393,0.005840,0.002714
3,0.001863,0.001234,-0.003304,-0.007703,-0.000645,0.002725,-0.000178,0.000003,0.002596,-0.006420,...,-0.000983,-0.001286,-0.001210,-0.000396,-0.000702,-0.000484,-0.000409,-0.000393,0.004174,0.002714
4,0.001219,-0.001040,-0.002409,-0.004260,0.000723,0.008469,0.004208,0.009455,-0.000475,0.000226,...,0.001612,0.001409,0.000139,-0.000396,-0.000702,-0.000484,-0.000409,-0.000393,0.005615,0.002714

In [9]:
X_train.shape

(527073, 56)

In [15]:
from feature_eng import add_rowwise_features
X_train, X_test, features = add_rowwise_features(X_train, X_test, features)
len(features)

77

In [16]:
X_train[features].head()

,RET_1,RET_2,RET_3,RET_4,RET_5,RET_6,RET_7,RET_8,RET_9,RET_10,...,vol_max_20,vol_pos_count_20,vol_mean_3,vol_mean_5,vol_mean_10,vol_trend_1_minus_5,vol_trend_5_minus_20,ret5_x_turnover,vol5_x_turnover,absret20_to_turnover
ROW_ID,,,,,,,,,,,,,,,,,,,,,
0,0.003944,-0.000178,0.001013,0.001514,-0.009067,0.002864,-0.009116,0.003312,0.001350,-0.009898,...,1.208587,16,0.072136,0.086381,0.336413,NaN,-0.526921,-0.000054,0.008371,0.042611
1,0.002323,0.000670,0.001383,-0.003427,0.000577,0.003323,0.003926,0.002878,-0.000259,-0.000376,...,-0.636931,0,-0.733898,-0.794794,-1.100634,NaN,1.006714,0.000003,-0.007927,0.204580
2,-0.000238,-0.002696,-0.003926,-0.000569,-0.002528,0.004384,-0.011090,-0.002392,0.006396,-0.006482,...,1.669319,19,0.380808,0.736525,0.816540,NaN,-0.131491,-0.000088,0.032544,0.109356
3,0.001863,0.001234,-0.003304,-0.007703,-0.000645,0.002725,-0.000178,0.000003,0.002596,-0.006420,...,-0.349882,0,-0.718917,-0.929260,-0.732850,NaN,-0.106361,-0.000002,-0.001069,2.966929
4,0.001219,-0.001040,-0.002409,-0.004260,0.000723,0.008469,0.004208,0.009455,-0.000475,0.000226,...,3.112834,13,0.992271,1.278511,0.908251,NaN,0.737191,NaN,NaN,NaN

In [17]:
X_train.shape

(527073, 80)

In [20]:
import feature_eng
from importlib import reload

reload(feature_eng)
print(dir(feature_eng))

['FE_benchmark', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'add_rowwise_features', 'add_temporal_FE']

In [21]:
from feature_eng import add_temporal_FE